"""CadQuery script generator and in-process model builder for Agent 6 (CAD Generation).

Generates CadQuery Python scripts and builds models in-process for STEP/STL export.
"""

from __future__ import annotations

import logging
from typing import Any

from geometra.agents.agent_06.openscad_gen import DEFAULT_THICKNESS

logger = logging.getLogger(__name__)

# ── CadQuery lazy import ─────────────────────────────────────────────────────

try:
    import cadquery as cq

    CADQUERY_AVAILABLE = True
except ImportError:
    CADQUERY_AVAILABLE = False
    logger.info("CadQuery not installed; STEP/STL export disabled. Install with: pip install cadquery")


def get_cadquery() -> Any | None:
    """Return the cadquery module if available, or None.

    Used by agent.py to access cq.exporters.export() without needing
    its own import of cadquery.
    """
    if CADQUERY_AVAILABLE:
        return cq
    return None


def generate_cadquery_script(
    operations: list[dict[str, Any]],
    parameters: dict[str, Any],
) -> str:
    """Generate a CadQuery Python script from the feature tree operations.

    The script defines a function `build_model()` that returns a CadQuery
    Workplane, and a `main()` block that exports to STEP and STL.

    Args:
        operations: List of CAD operation dicts from Agent 5.
        parameters: Global parameters dict.

    Returns:
        Complete CadQuery Python script as a string.
    """
    body_w = parameters.get("body_width", 100.0)
    body_h = parameters.get("body_height", 100.0)
    thickness = parameters.get("body_thickness", DEFAULT_THICKNESS)
    if not body_w or body_w <= 0:
        body_w = 100.0
    if not body_h or body_h <= 0:
        body_h = 100.0

    lines: list[str] = []
    _line = lines.append
    _line('"""Parametric CAD model generated by Geometra Agent 6."""')
    _line("")
    _line("import cadquery as cq")
    _line("")
    _line("# ── Parameters ────────────────────────────────────────────────")
    _line(f"BODY_W = {body_w}")
    _line(f"BODY_H = {body_h}")
    _line(f"T = {thickness}")
    _line("")

    # Count operations for variable names
    hole_n = 0
    slot_n = 0
    cutout_n = 0
    pocket_n = 0
    vent_n = 0
    boss_n = 0
    fillet_n = 0
    chamfer_n = 0

    # Conslidate operations into script lines
    _line("def build_model():")
    _line(f"    result = cq.Workplane('XY').box(BODY_W, BODY_H, T)")
    _line("")

    for op in operations:
        op_type = op.get("operation", "")
        fid = op.get("feature_id", "feature")

        if op_type == "drill":
            x = op.get("x", 0)
            y = op.get("y", 0)
            r = op.get("radius", 5)
            hole_n += 1
            offset_x = x - body_w / 2
            offset_y = y - body_h / 2
            _line(f"    # {fid}: drill hole at ({x}, {y}), r={r}")
            _line(
                f"    result = result.faces('<Z').workplane()"
                f".center({offset_x}, {offset_y})"
                f".hole(diameter={r*2}, depth=T)"
            )
            _line("")

        elif op_type == "mill":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 10)
            h = op.get("height", 5)
            slot_n += 1
            offset_x = x - body_w / 2
            offset_y = y - body_h / 2
            _line(f"    # {fid}: mill slot at ({x}, {y}), {w} x {h}")
            _line(
                f"    result = result.faces('<Z').workplane()"
                f".center({offset_x}, {offset_y})"
                f".rect({w}, {h})"
                f".cutBlind(-T)"
            )
            _line("")

        elif op_type == "cut":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 20)
            h = op.get("height", 20)
            cutout_n += 1
            offset_x = x - body_w / 2
            offset_y = y - body_h / 2
            _line(f"    # {fid}: cutout at ({x}, {y}), {w} x {h}")
            _line(
                f"    result = result.faces('<Z').workplane()"
                f".center({offset_x}, {offset_y})"
                f".rect({w}, {h})"
                f".cutThruAll()"
            )
            _line("")

        elif op_type == "pocket_mill":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 10)
            h = op.get("height", 10)
            depth = op.get("depth", thickness / 2)
            pocket_n += 1
            offset_x = x - body_w / 2
            offset_y = y - body_h / 2
            _line(f"    # {fid}: pocket at ({x}, {y}), {w} x {h}, depth {depth}")
            _line(
                f"    result = result.faces('<Z').workplane()"
                f".center({offset_x}, {offset_y})"
                f".rect({w}, {h})"
                f".cutBlind(-{depth})"
            )
            _line("")

        elif op_type == "vent_cut":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 20)
            h = op.get("height", 40)
            slot_count_val = op.get("slot_count", 5)
            orientation = op.get("orientation", "horizontal")
            vent_n += 1
            _line(f"    # {fid}: vent at ({x}, {y}), {slot_count_val} slots, {orientation}")
            if orientation == "horizontal":
                spacing = h / (slot_count_val + 1)
                slot_h = max(2.0, spacing * 0.5)
                for vi in range(slot_count_val):
                    sy = y - h / 2 + spacing * (vi + 1)
                    off_x = x - body_w / 2
                    off_y = sy - body_h / 2
                    _line(
                        f"    result = result.faces('<Z').workplane()"
                        f".center({off_x}, {off_y})"
                        f".rect({w}, {slot_h})"
                        f".cutThruAll()"
                    )
            else:
                spacing = w / (slot_count_val + 1)
                slot_w = max(2.0, spacing * 0.5)
                for vi in range(slot_count_val):
                    sx = x - w / 2 + spacing * (vi + 1)
                    off_x = sx - body_w / 2
                    off_y = y - body_h / 2
                    _line(
                        f"    result = result.faces('<Z').workplane()"
                        f".center({off_x}, {off_y})"
                        f".rect({slot_w}, {h})"
                        f".cutThruAll()"
                    )
            _line("")

        elif op_type == "boss_extrude":
            x = op.get("x", 0)
            y = op.get("y", 0)
            r = op.get("radius", 10)
            height = op.get("height", thickness * 0.5)
            boss_n += 1
            offset_x = x - body_w / 2
            offset_y = y - body_h / 2
            _line(f"    # {fid}: boss at ({x}, {y}), r={r}, h={height}")
            _line(
                f"    result = result.faces('>Z').workplane()"
                f".center({offset_x}, {offset_y})"
                f".circle({r})"
                f".extrude({height})"
            )
            _line("")

        elif op_type == "fillet":
            r = op.get("radius", 3)
            fillet_n += 1
            _line(f"    # {fid}: fillet r={r} — applies to all vertical edges")
            _line(f"    result = result.edges('|Z').fillet({r})")
            _line("")

        elif op_type == "chamfer":
            length = op.get("length", 2)
            chamfer_n += 1
            _line(f"    # {fid}: chamfer length={length} — applies to top edges")
            _line(f"    result = result.edges('>Z').chamfer({length})")
            _line("")

    _line("    return result")
    _line("")
    _line("")
    _line('if __name__ == "__main__":')
    _line('    model = build_model()')
    _line('    cq.exporters.export(model, "output.step")')
    _line('    cq.exporters.export(model, "output.stl", tolerance=0.1)')

    return "\n".join(lines)


def build_cadquery_model(
    operations: list[dict[str, Any]],
    parameters: dict[str, Any],
) -> Any | None:
    """Build a CadQuery model in-process and return the Workplane.

    Returns None if CadQuery is not available.

    Args:
        operations: List of CAD operation dicts from Agent 5.
        parameters: Global parameters dict.

    Returns:
        CadQuery Workplane, or None if unavailable.
    """
    if not CADQUERY_AVAILABLE:
        return None

    body_w = parameters.get("body_width", 100.0)
    body_h = parameters.get("body_height", 100.0)
    thickness = parameters.get("body_thickness", DEFAULT_THICKNESS)
    if not body_w or body_w <= 0:
        body_w = 100.0
    if not body_h or body_h <= 0:
        body_h = 100.0

    result = cq.Workplane("XY").box(body_w, body_h, thickness)

    for op in operations:
        try:
            op_type = op.get("operation", "")

            if op_type == "drill":
                x = op.get("x", 0)
                y = op.get("y", 0)
                r = op.get("radius", 5)
                offset_x = x - body_w / 2
                offset_y = y - body_h / 2
                result = (
                    result.faces("<Z")
                    .workplane()
                    .center(offset_x, offset_y)
                    .hole(diameter=r * 2, depth=thickness)
                )

            elif op_type == "mill":
                x = op.get("x", 0)
                y = op.get("y", 0)
                w = op.get("width", 10)
                h = op.get("height", 5)
                offset_x = x - body_w / 2
                offset_y = y - body_h / 2
                result = (
                    result.faces("<Z")
                    .workplane()
                    .center(offset_x, offset_y)
                    .rect(w, h)
                    .cutBlind(-thickness)
                )

            elif op_type == "cut":
                x = op.get("x", 0)
                y = op.get("y", 0)
                w = op.get("width", 20)
                h = op.get("height", 20)
                offset_x = x - body_w / 2
                offset_y = y - body_h / 2
                result = (
                    result.faces("<Z")
                    .workplane()
                    .center(offset_x, offset_y)
                    .rect(w, h)
                    .cutThruAll()
                )

            elif op_type == "pocket_mill":
                x = op.get("x", 0)
                y = op.get("y", 0)
                w = op.get("width", 10)
                h = op.get("height", 10)
                depth = op.get("depth", thickness / 2)
                offset_x = x - body_w / 2
                offset_y = y - body_h / 2
                result = (
                    result.faces("<Z")
                    .workplane()
                    .center(offset_x, offset_y)
                    .rect(w, h)
                    .cutBlind(-depth)
                )

            elif op_type == "vent_cut":
                x = op.get("x", 0)
                y = op.get("y", 0)
                w = op.get("width", 20)
                h = op.get("height", 40)
                slot_count_val = op.get("slot_count", 5)
                orientation = op.get("orientation", "horizontal")
                if orientation == "horizontal":
                    spacing = h / (slot_count_val + 1)
                    slot_h = max(2.0, spacing * 0.5)
                    for vi in range(slot_count_val):
                        sy = y - h / 2 + spacing * (vi + 1)
                        off_x = x - body_w / 2
                        off_y = sy - body_h / 2
                        result = (
                            result.faces("<Z")
                            .workplane()
                            .center(off_x, off_y)
                            .rect(w, slot_h)
                            .cutThruAll()
                        )
                else:
                    spacing = w / (slot_count_val + 1)
                    slot_w = max(2.0, spacing * 0.5)
                    for vi in range(slot_count_val):
                        sx = x - w / 2 + spacing * (vi + 1)
                        off_x = sx - body_w / 2
                        off_y = y - body_h / 2
                        result = (
                            result.faces("<Z")
                            .workplane()
                            .center(off_x, off_y)
                            .rect(slot_w, h)
                            .cutThruAll()
                        )

            elif op_type == "boss_extrude":
                x = op.get("x", 0)
                y = op.get("y", 0)
                r = op.get("radius", 10)
                height = op.get("height", thickness * 0.5)
                offset_x = x - body_w / 2
                offset_y = y - body_h / 2
                result = (
                    result.faces(">Z")
                    .workplane()
                    .center(offset_x, offset_y)
                    .circle(r)
                    .extrude(height)
                )

            elif op_type == "fillet":
                r = op.get("radius", 3)
                result = result.edges("|Z").fillet(r)

            elif op_type == "chamfer":
                length = op.get("length", 2)
                result = result.edges(">Z").chamfer(length)
        except Exception:
            logger.warning(
                "CadQuery operation '%s' failed for '%s': %s",
                op.get("operation", "?"),
                op.get("feature_id", "?"),
                exc_info=True,
            )

    return result
