"""OpenSCAD script generator for Agent 6 (CAD Generation).

Generates OpenSCAD scripts from a parametric feature tree, producing a
flat plate with all subtractive and additive operations applied.
"""

from __future__ import annotations

from typing import Any

# ── Default material thickness for 2D-extruded models ─────────────────────────
DEFAULT_THICKNESS = 5.0  # mm


def generate_openscad(
    operations: list[dict[str, Any]],
    parameters: dict[str, Any],
) -> str:
    """Generate an OpenSCAD script from the feature tree operations.

    The script creates a flat plate (extruded from 2D) with all
    subtractive and additive operations applied.

    Args:
        operations: List of CAD operation dicts from Agent 5.
        parameters: Global parameters dict (body_width, body_height, etc.).

    Returns:
        Complete OpenSCAD script as a string.
    """
    body_w = parameters.get("body_width", 100.0)
    body_h = parameters.get("body_height", 100.0)
    thickness = parameters.get("body_thickness", DEFAULT_THICKNESS)
    # Default body dimensions if unset
    if not body_w or body_w <= 0:
        body_w = 100.0
    if not body_h or body_h <= 0:
        body_h = 100.0

    lines: list[str] = []
    _open_line = lines.append
    _open_line("// Generated by Geometra Agent 6 (CAD Generation)")
    _open_line(f"// Body: {body_w} x {body_h} x {thickness} mm")
    _open_line("")
    _open_line(f"body_w = {body_w};")
    _open_line(f"body_h = {body_h};")
    _open_line(f"t = {thickness};")
    _open_line("$fn = 50;  // circle resolution")
    _open_line("")

    # Collect subtractive and additive operations
    subtractive_ops: list[str] = []
    additive_ops: list[str] = []
    hole_count = 0
    slot_count = 0
    cutout_count = 0
    pocket_count = 0
    vent_count = 0
    boss_count = 0
    fillet_count = 0
    chamfer_count = 0

    for op in operations:
        op_type = op.get("operation", "")
        fid = op.get("feature_id", "feature")

        if op_type == "drill":
            x = op.get("x", 0)
            y = op.get("y", 0)
            r = op.get("radius", 5)
            hole_count += 1
            name = f"hole_{hole_count}"
            subtractive_ops.append(
                f"    // {name}: {fid} at ({x}, {y}), r={r}\n"
                f"    translate([{x}, {y}, -0.1])\n"
                f"        cylinder(h=t+0.2, r={r}, $fn=50);"
            )

        elif op_type == "mill":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 10)
            h = op.get("height", 5)
            slot_count += 1
            name = f"slot_{slot_count}"
            subtractive_ops.append(
                f"    // {name}: {fid} at ({x}, {y}), {w} x {h}\n"
                f"    translate([{x - w/2}, {y - h/2}, -0.1])\n"
                f"        cube([{w}, {h}, t+0.2]);"
            )

        elif op_type == "cut":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 20)
            h = op.get("height", 20)
            cutout_count += 1
            name = f"cutout_{cutout_count}"
            subtractive_ops.append(
                f"    // {name}: {fid} at ({x}, {y}), {w} x {h}\n"
                f"    translate([{x - w/2}, {y - h/2}, -0.1])\n"
                f"        cube([{w}, {h}, t+0.2]);"
            )

        elif op_type == "pocket_mill":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 10)
            h = op.get("height", 10)
            depth = op.get("depth", thickness / 2)
            pocket_count += 1
            name = f"pocket_{pocket_count}"
            subtractive_ops.append(
                f"    // {name}: {fid} at ({x}, {y}), {w} x {h}, depth {depth}\n"
                f"    translate([{x - w/2}, {y - h/2}, t - {depth} + 0.1])\n"
                f"        cube([{w}, {h}, {depth}]);"
            )

        elif op_type == "vent_cut":
            x = op.get("x", 0)
            y = op.get("y", 0)
            w = op.get("width", 20)
            h = op.get("height", 40)
            slot_count_val = op.get("slot_count", 5)
            orientation = op.get("orientation", "horizontal")
            vent_count += 1
            name = f"vent_{vent_count}"
            vent_lines = [f"    // {name}: {fid} at ({x}, {y}), {slot_count_val} slots, {orientation}"]
            if orientation == "horizontal":
                spacing = h / (slot_count_val + 1)
                slot_h = max(2.0, spacing * 0.5)
                for vi in range(slot_count_val):
                    sy = y - h / 2 + spacing * (vi + 1) - slot_h / 2
                    vent_lines.append(
                        f"    translate([{x - w/2}, {sy}, -0.1])\n"
                        f"        cube([{w}, {slot_h}, t+0.2]);"
                    )
            else:
                spacing = w / (slot_count_val + 1)
                slot_w = max(2.0, spacing * 0.5)
                for vi in range(slot_count_val):
                    sx = x - w / 2 + spacing * (vi + 1) - slot_w / 2
                    vent_lines.append(
                        f"    translate([{sx}, {y - h/2}, -0.1])\n"
                        f"        cube([{slot_w}, {h}, t+0.2]);"
                    )
            subtractive_ops.append("\n".join(vent_lines))

        elif op_type == "boss_extrude":
            x = op.get("x", 0)
            y = op.get("y", 0)
            r = op.get("radius", 10)
            height = op.get("height", thickness * 0.5)
            boss_count += 1
            name = f"boss_{boss_count}"
            additive_ops.append(
                f"    // {name}: {fid} at ({x}, {y}), r={r}, h={height}\n"
                f"    translate([{x}, {y}, t])\n"
                f"        cylinder(h={height}, r={r}, $fn=50);"
            )

        elif op_type == "fillet":
            x = op.get("x", 0)
            y = op.get("y", 0)
            r = op.get("radius", 3)
            fillet_count += 1
            name = f"fillet_{fillet_count}"
            # Fillets are annotations in OpenSCAD — noted in comments
            _open_line(f"// {name}: {fid} fillet r={r} at ({x}, {y}) — apply manually in OpenSCAD GUI")

        elif op_type == "chamfer":
            x1 = op.get("x1", 0)
            y1 = op.get("y1", 0)
            x2 = op.get("x2", 0)
            y2 = op.get("y2", 0)
            chamfer_count += 1
            name = f"chamfer_{chamfer_count}"
            _open_line(f"// {name}: {fid} chamfer from ({x1},{y1}) to ({x2},{y2}) — apply manually in OpenSCAD GUI")

    # ── Build the body with all subtractive operations ──
    _open_line("// Base body with holes and cutouts")
    if subtractive_ops:
        _open_line("difference() {")
        _open_line("    // Main body plate")
        _open_line(f"    cube([body_w, body_h, t]);")
        for op_block in subtractive_ops:
            for op_line in op_block.split("\n"):
                _open_line(f"    {op_line.lstrip()}" if not op_line.startswith("    ") else op_line)
        _open_line("}")
    else:
        _open_line(f"cube([body_w, body_h, t]);")

    # ── Add additive operations ──
    if additive_ops:
        _open_line("")
        _open_line("// Additive features (bosses)")
        _open_line("union() {")
        _open_line("    // Re-create body (can't union with difference easily)")
        if subtractive_ops:
            _open_line("    difference() {")
            _open_line(f"        cube([body_w, body_h, t]);")
            for op_block in subtractive_ops:
                for op_line in op_block.split("\n"):
                    _open_line(f"        {op_line.lstrip()}" if not op_line.startswith("        ") else op_line)
            _open_line("    }")
        else:
            _open_line(f"    cube([body_w, body_h, t]);")
        for op_block in additive_ops:
            for op_line in op_block.split("\n"):
                _open_line(f"    {op_line.lstrip()}" if not op_line.startswith("    ") else op_line)
        _open_line("}")

    _open_line("")
    _open_line("// Rendering hints")
    body_txt = f"Body: {body_w}x{body_h}x{thickness}mm"
    rendered_count = hole_count + slot_count + cutout_count + pocket_count + vent_count + boss_count
    notes = [body_txt]
    if fillet_count:
        notes.append(f"{fillet_count} fillet(s) — F5 preview, use fillet() in OpenSCAD GUI")
    if chamfer_count:
        notes.append(f"{chamfer_count} chamfer(s) — use chamfer() in OpenSCAD GUI")
    if rendered_count:
        notes.append(f"{rendered_count} features rendered")
    _open_line(f"// Notes: {'; '.join(notes)}")

    return "\n".join(lines)
