"""Unit tests for the CAD Generation Agent (Agent 6).

Tests cover:
- OpenSCAD script generation for all 8 operation types
- CadQuery script generation for all 8 operation types
- Agent pipeline integration (receiving Agent 5 output)
- Edge cases: empty operations, no body dimensions, all feature types
- CadQuery availability detection
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from geometra.agents.agent_06 import CADGenerationAgent
from geometra.agents.agent_06.cadquery_gen import (
    CADQUERY_AVAILABLE,
    build_cadquery_model,
    generate_cadquery_script,
)
from geometra.agents.agent_06.openscad_gen import generate_openscad


# ── Agent Fixture ─────────────────────────────────────────────────────────────


@pytest.fixture
def agent() -> CADGenerationAgent:
    return CADGenerationAgent()


# ── Synthetic Input Fixtures ─────────────────────────────────────────────────


@pytest.fixture
def empty_tree() -> dict:
    return {"operations": [], "parameters": {}}


@pytest.fixture
def hole_only_tree() -> dict:
    return {
        "operations": [
            {
                "operation": "drill",
                "feature_id": "hole_100_120",
                "x": 100.0,
                "y": 120.0,
                "radius": 30.0,
                "depth": "through",
            },
        ],
        "parameters": {"body_width": 400.0, "body_height": 350.0},
    }


@pytest.fixture
def all_operations_tree() -> dict:
    """Input with all 8 operation types plus body dimensions."""
    return {
        "operations": [
            {"operation": "drill", "feature_id": "hole_1", "x": 100, "y": 120, "radius": 30, "depth": "through"},
            {"operation": "drill", "feature_id": "hole_2", "x": 200, "y": 120, "radius": 20, "depth": "through"},
            {"operation": "mill", "feature_id": "slot_1", "x": 150, "y": 100, "width": 80, "height": 20},
            {"operation": "cut", "feature_id": "cutout_1", "x": 250, "y": 140, "width": 200, "height": 120},
            {"operation": "pocket_mill", "feature_id": "pocket_1", "x": 180, "y": 180, "width": 60, "height": 60},
            {"operation": "vent_cut", "feature_id": "vent_1", "x": 150, "y": 250, "width": 100, "height": 80,
             "slot_count": 5, "orientation": "horizontal"},
            {"operation": "boss_extrude", "feature_id": "boss_1", "x": 300, "y": 80, "radius": 25},
            {"operation": "fillet", "feature_id": "fillet_1", "x": 50, "y": 50, "radius": 5},
            {"operation": "chamfer", "feature_id": "chamfer_1", "x1": 100, "y1": 100, "x2": 115, "y2": 85,
             "length": 5},
        ],
        "parameters": {"body_width": 440.0, "body_height": 340.0},
    }


# ── ValidateInput Tests ──────────────────────────────────────────────────────


class TestValidateInput:
    def test_valid_tree(self, agent: CADGenerationAgent, hole_only_tree: dict) -> None:
        assert agent.validate_input(hole_only_tree) is True

    def test_empty_operations(self, agent: CADGenerationAgent) -> None:
        assert agent.validate_input({"operations": []}) is True

    def test_missing_operations(self, agent: CADGenerationAgent) -> None:
        assert agent.validate_input({"parameters": {}}) is False

    def test_none(self, agent: CADGenerationAgent) -> None:
        assert agent.validate_input(None) is False

    def test_string(self, agent: CADGenerationAgent) -> None:
        assert agent.validate_input("bad input") is False


# ── OpenSCAD Script Generation ───────────────────────────────────────────────


class TestOpenSCADGeneration:
    def test_generates_valid_openscad(self, hole_only_tree: dict) -> None:
        script = generate_openscad(hole_only_tree["operations"], hole_only_tree["parameters"])
        assert isinstance(script, str)
        assert len(script) > 0
        assert "Generated by Geometra" in script
        assert "body_w = 400.0" in script
        assert "body_h = 350.0" in script

    def test_includes_cylinder_for_hole(self, hole_only_tree: dict) -> None:
        script = generate_openscad(hole_only_tree["operations"], hole_only_tree["parameters"])
        assert "cylinder" in script
        assert "hole_100_120" in script
        assert "radius" in script or "r=" in script.lower()

    def test_empty_operations(self) -> None:
        script = generate_openscad([], {})
        assert "cube([100, 100, 5.0])" in script or "cube(" in script

    def test_body_dimensions_default_when_missing(self) -> None:
        script = generate_openscad([], {})
        # Should use default 100x100 body when no dimensions
        assert "body_w = 100" in script
        assert "body_h = 100" in script

    def test_all_operation_types(self, all_operations_tree: dict) -> None:
        script = generate_openscad(
            all_operations_tree["operations"],
            all_operations_tree["parameters"],
        )
        # Each operation type should be mentioned in comments
        assert "drill" in script or "hole" in script
        assert "mill" in script or "slot" in script
        assert "cutout" in script
        assert "pocket" in script
        assert "vent" in script
        assert "boss" in script
        assert "fillet" in script
        assert "chamfer" in script
        # Body dimensions should be correct
        assert "body_w = 440.0" in script
        assert "body_h = 340.0" in script

    def test_openscad_has_difference_block(self, all_operations_tree: dict) -> None:
        """Subtractive operations should be wrapped in a difference() block."""
        script = generate_openscad(
            all_operations_tree["operations"],
            all_operations_tree["parameters"],
        )
        assert "difference()" in script

    def test_openscad_no_difference_for_empty(self) -> None:
        """No difference block needed when there are no subtractive operations."""
        script = generate_openscad([], {"body_width": 100, "body_height": 100})
        assert "difference()" not in script

    def test_vent_horizontal_slots(self) -> None:
        ops = [{
            "operation": "vent_cut", "feature_id": "vent_1",
            "x": 150, "y": 250, "width": 100, "height": 80,
            "slot_count": 3, "orientation": "horizontal",
        }]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        # Should have 3 translate blocks for 3 vent slots
        assert script.count("translate([") >= 3

    def test_vent_vertical_slots(self) -> None:
        ops = [{
            "operation": "vent_cut", "feature_id": "vent_1",
            "x": 150, "y": 250, "width": 80, "height": 100,
            "slot_count": 3, "orientation": "vertical",
        }]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        assert script.count("translate([") >= 3

    def test_boss_additive(self) -> None:
        """Boss should be added, not subtracted."""
        ops = [{"operation": "boss_extrude", "feature_id": "boss_1",
                "x": 300, "y": 80, "radius": 25}]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        assert "cylinder" in script
        assert "Additive features" in script or "union" in script.lower()


# ── CadQuery Script Generation (text output only) ────────────────────────────


class TestCadQueryScriptGeneration:
    def test_generates_valid_python(self, hole_only_tree: dict) -> None:
        script = generate_cadquery_script(
            hole_only_tree["operations"],
            hole_only_tree["parameters"],
        )
        assert isinstance(script, str)
        assert len(script) > 0
        assert "import cadquery as cq" in script

    def test_has_build_model_function(self, hole_only_tree: dict) -> None:
        script = generate_cadquery_script(
            hole_only_tree["operations"],
            hole_only_tree["parameters"],
        )
        assert "def build_model():" in script
        assert "return result" in script

    def test_includes_export_block(self, hole_only_tree: dict) -> None:
        script = generate_cadquery_script(
            hole_only_tree["operations"],
            hole_only_tree["parameters"],
        )
        assert 'if __name__ == "__main__":' in script
        assert "cq.exporters.export" in script

    def test_hole_translation(self) -> None:
        """Hole at (100, 120) on 400x350 body -> offset (100-200, 120-175) = (-100, -55)."""
        ops = [{"operation": "drill", "feature_id": "hole_1", "x": 100, "y": 120, "radius": 30, "depth": "through"}]
        params = {"body_width": 400.0, "body_height": 350.0}
        script = generate_cadquery_script(ops, params)
        # The offset from center: x-200=-100, y-175=-55
        assert ".center(-100" in script or ".center(-100" in script

    def test_all_operation_types(self, all_operations_tree: dict) -> None:
        script = generate_cadquery_script(
            all_operations_tree["operations"],
            all_operations_tree["parameters"],
        )
        assert "def build_model():" in script
        assert "hole(diameter" in script or ".hole(" in script
        assert "cutBlind" in script or "cutThruAll" in script
        assert "extrude" in script
        assert "fillet" in script
        assert "chamfer" in script

    def test_empty_operations(self) -> None:
        script = generate_cadquery_script([], {})
        assert "def build_model():" in script
        assert ".box(" in script  # body box


# ── CadQuery In-Process Model Building ───────────────────────────────────────


class TestCadQueryModel:
    def test_cadquery_is_available(self) -> None:
        """CadQuery is installed and available."""
        assert CADQUERY_AVAILABLE is True

    def test_build_empty_model(self) -> None:
        """Building an empty model returns a Workplane with valid shape."""
        model = build_cadquery_model([], {})
        assert model is not None
        assert hasattr(model, "val")
        # Default 100x100x5 box — Volume() is a method in CadQuery 2.7
        shape = model.val()
        assert shape is not None
        vol = float(shape.Volume())
        assert abs(vol - 100 * 100 * 5.0) < 1.0

    def test_build_with_body_dimensions(self) -> None:
        """Body dimensions should produce correct volume."""
        params = {"body_width": 200.0, "body_height": 150.0, "body_thickness": 8.0}
        model = build_cadquery_model([], params)
        shape = model.val()
        vol = float(shape.Volume())
        assert abs(vol - 200 * 150 * 8.0) < 1.0

    def test_build_model_with_hole(self) -> None:
        """A drill hole should reduce the volume."""
        body_w, body_h, t = 100.0, 80.0, 5.0
        ops = [{"operation": "drill", "x": 50, "y": 40, "radius": 10.0, "depth": "through"}]
        params = {"body_width": body_w, "body_height": body_h, "body_thickness": t}
        model = build_cadquery_model(ops, params)
        shape = model.val()
        full_volume = body_w * body_h * t
        hole_volume = 3.14159 * 10.0**2 * t
        vol = float(shape.Volume())
        assert vol < full_volume - hole_volume * 0.9  # at least 90% of hole removed

    def test_build_model_with_hole_only(self) -> None:
        """Building a model with a single drill hole."""
        ops = [{"operation": "drill", "x": 50, "y": 40, "radius": 10.0, "depth": "through"}]
        params = {"body_width": 100.0, "body_height": 80.0, "body_thickness": 5.0}
        model = build_cadquery_model(ops, params)
        assert model is not None
        shape = model.val()
        assert float(shape.Volume()) > 0

    def test_build_model_with_slot(self) -> None:
        """Building a model with a mill slot."""
        ops = [{"operation": "mill", "x": 50, "y": 40, "width": 20, "height": 10}]
        params = {"body_width": 100.0, "body_height": 80.0, "body_thickness": 5.0}
        model = build_cadquery_model(ops, params)
        assert model is not None
        shape = model.val()
        assert float(shape.Volume()) > 0

    def test_build_model_with_cutout(self) -> None:
        """Building a model with a through cutout."""
        ops = [{"operation": "cut", "x": 50, "y": 40, "width": 60, "height": 30}]
        params = {"body_width": 100.0, "body_height": 80.0, "body_thickness": 5.0}
        model = build_cadquery_model(ops, params)
        assert model is not None
        shape = model.val()
        assert float(shape.Volume()) > 0

    def test_build_model_with_boss(self) -> None:
        """Building a model with a boss extrude."""
        ops = [{"operation": "boss_extrude", "x": 50, "y": 40, "radius": 15, "height": 5}]
        params = {"body_width": 100.0, "body_height": 80.0, "body_thickness": 5.0}
        model = build_cadquery_model(ops, params)
        assert model is not None
        shape = model.val()
        assert float(shape.Volume()) > 0

    def test_build_model_with_fillet(self) -> None:
        """Building a model with a fillet operation."""
        ops = [{"operation": "fillet", "radius": 2}]
        params = {"body_width": 100.0, "body_height": 80.0, "body_thickness": 5.0}
        model = build_cadquery_model(ops, params)
        assert model is not None


# ── Full Agent Pipeline ──────────────────────────────────────────────────────


class TestFullPipeline:
    def test_agent_process_hole(self, agent: CADGenerationAgent, hole_only_tree: dict) -> None:
        result = agent.process(hole_only_tree)
        assert isinstance(result, dict)
        assert result["success"] is True
        assert "openscad_script" in result
        assert "cadquery_script" in result
        assert "output_paths" in result
        assert "formats" in result
        assert result["feature_count"] == 1

    def test_agent_process_all_types(self, agent: CADGenerationAgent, all_operations_tree: dict) -> None:
        result = agent.process(all_operations_tree)
        assert result["success"] is True
        assert result["feature_count"] == 9
        assert "scad" in result["formats"]
        assert "py" in result["formats"]

    def test_agent_process_empty(self, agent: CADGenerationAgent, empty_tree: dict) -> None:
        result = agent.process(empty_tree)
        assert result["success"] is True
        assert result["feature_count"] == 0

    def test_cadquery_is_used(self, agent: CADGenerationAgent, hole_only_tree: dict) -> None:
        result = agent.process(hole_only_tree)
        assert result["cadquery_used"] is True

    def test_generate_writes_files(self, agent: CADGenerationAgent, hole_only_tree: dict, tmp_path: Path) -> None:
        result = agent.generate(hole_only_tree, output_dir=str(tmp_path))
        assert result["success"] is True
        # Check that files were written
        scad_path = result["output_paths"].get("scad", "")
        if scad_path:
            assert Path(scad_path).exists()
        cq_path = result["output_paths"].get("cadquery_py", "")
        if cq_path:
            assert Path(cq_path).exists()

    def test_generate_writes_step_stl(self, agent: CADGenerationAgent, hole_only_tree: dict, tmp_path: Path) -> None:
        """With CadQuery available, generate() should produce step and stl files."""
        result = agent.generate(hole_only_tree, output_dir=str(tmp_path))
        assert result["success"] is True
        assert result["cadquery_used"] is True
        paths = result["output_paths"]
        assert "step" in paths
        assert "stl" in paths
        assert Path(paths["step"]).exists()
        assert Path(paths["stl"]).exists()
        step_size = Path(paths["step"]).stat().st_size
        stl_size = Path(paths["stl"]).stat().st_size
        assert step_size > 100, f"STEP file too small: {step_size} bytes"
        assert stl_size > 100, f"STL file too small: {stl_size} bytes"

    def test_export_step_flag_false(self, agent: CADGenerationAgent, hole_only_tree: dict, tmp_path: Path) -> None:
        """Setting export_step=False should skip step export even with CadQuery."""
        result = agent.generate(hole_only_tree, output_dir=str(tmp_path),
                                export_step=False, export_stl=False)
        assert result["success"] is True
        assert "step" not in result["formats"]
        assert "stl" not in result["formats"]
        assert "scad" in result["formats"]
        assert "py" in result["formats"]

    def test_step_export_contains_correct_header(self, agent: CADGenerationAgent, hole_only_tree: dict, tmp_path: Path) -> None:
        """STEP file should be a valid ISO 10303-21 file."""
        result = agent.generate(hole_only_tree, output_dir=str(tmp_path))
        step_path = Path(result["output_paths"]["step"])
        step_text = step_path.read_text(encoding="utf-8", errors="replace")
        assert "ISO-10303-21" in step_text, "STEP file missing required header"
        assert "HEADER" in step_text

    def test_stl_export_exists_and_has_content(self, agent: CADGenerationAgent, hole_only_tree: dict, tmp_path: Path) -> None:
        """STL file should be written to disk and have content."""
        result = agent.generate(hole_only_tree, output_dir=str(tmp_path))
        stl_path = Path(result["output_paths"]["stl"])
        assert stl_path.exists()
        assert stl_path.stat().st_size > 100

    def test_generate_with_thickness_override(self, agent: CADGenerationAgent, hole_only_tree: dict) -> None:
        result = agent.generate(hole_only_tree, thickness=10.0)
        script = result["openscad_script"]
        assert "t = 10.0" in script

    def test_openscad_script_includes_body_thickness(self, agent: CADGenerationAgent) -> None:
        result = agent.process({"operations": [], "parameters": {"body_thickness": 3.0}})
        assert "t = 3.0" in result["openscad_script"]

    def test_cadquery_script_includes_body_thickness(self, agent: CADGenerationAgent) -> None:
        result = agent.process({"operations": [], "parameters": {"body_thickness": 3.0}})
        assert "T = 3.0" in result["cadquery_script"]

    def test_reprocess_does_not_error(self, agent: CADGenerationAgent, all_operations_tree: dict) -> None:
        """Process should work correctly when called multiple times."""
        r1 = agent.process(all_operations_tree)
        r2 = agent.process(all_operations_tree)
        assert r1["success"] and r2["success"]
        assert r1["feature_count"] == r2["feature_count"]

    def test_output_paths_keys(self, agent: CADGenerationAgent, hole_only_tree: dict) -> None:
        result = agent.process(hole_only_tree)
        paths = result["output_paths"]
        assert "scad" in paths  # OpenSCAD always generated
        assert "cadquery_py" in paths  # CadQuery script always generated


# ── Edge Cases ───────────────────────────────────────────────────────────────


class TestEdgeCases:
    def test_operations_without_body_dimensions(self, agent: CADGenerationAgent) -> None:
        """Operations should work even without body dimensions (use defaults)."""
        ops = [{"operation": "drill", "x": 10, "y": 10, "radius": 5}]
        result = agent.process({"operations": ops, "parameters": {}})
        assert result["success"] is True
        assert result["feature_count"] == 1
        assert "body_w = 100" in result["openscad_script"]

    def test_negative_coordinates_handled(self, agent: CADGenerationAgent) -> None:
        """Negative coordinates should not cause errors."""
        ops = [{"operation": "drill", "x": -10, "y": -20, "radius": 5}]
        result = agent.process({"operations": ops, "parameters": {"body_width": 200, "body_height": 200}})
        assert result["success"] is True

    def test_large_number_of_operations(self, agent: CADGenerationAgent) -> None:
        """Many operations should not cause issues."""
        ops = []
        for i in range(50):
            ops.append({"operation": "drill", "feature_id": f"hole_{i}",
                        "x": i * 10, "y": i * 5, "radius": 3})
        result = agent.process({"operations": ops, "parameters": {"body_width": 1000, "body_height": 1000}})
        assert result["success"] is True
        assert result["feature_count"] == 50

    def test_no_cadquery_export_flag(self, agent: CADGenerationAgent, hole_only_tree: dict) -> None:
        """Setting export_step=False should not attempt STEP export."""
        result = agent.generate(hole_only_tree, export_step=False, export_stl=False)
        assert result["success"] is True
        assert "step" not in result["formats"]
        assert "stl" not in result["formats"]
        # But scad and py should still be there
        assert "scad" in result["formats"]
        assert "py" in result["formats"]


# ── OpenSCAD CLI Syntax Validation ───────────────────────────────────────────


openscad_path = shutil.which("openscad") or shutil.which("openscad.com")
skip_no_openscad = pytest.mark.skipif(
    openscad_path is None,
    reason="OpenSCAD CLI not found on PATH — install from https://openscad.org to enable",
)


class TestOpenSCADSyntaxValidation:
    """Validate generated OpenSCAD scripts by compiling them with the openscad CLI.

    These tests are skipped if the OpenSCAD CLI is not installed on the system.
    Install it from https://openscad.org and ensure it's on your PATH.

    On Windows, use ``openscad.com`` (console wrapper) instead of ``openscad.exe``
    to properly handle stdin/stdout streams.
    """

    _openscad_exe: str = openscad_path or "openscad"
    _null_device: str = "nul" if sys.platform == "win32" else "/dev/null"

    @staticmethod
    def _run_openscad(script: str, tmp_path: Path) -> subprocess.CompletedProcess:
        """Write script to a .scad file and run openscad to validate syntax."""
        scad_file = tmp_path / "test_validation.scad"
        scad_file.write_text(script, encoding="utf-8")
        result = subprocess.run(
            [TestOpenSCADSyntaxValidation._openscad_exe,
             "-o", TestOpenSCADSyntaxValidation._null_device,
             "-q",
             "--hardwarnings",
             str(scad_file)],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return result

    # ── Body only ──

    @skip_no_openscad
    def test_body_only_compiles(self, tmp_path: Path) -> None:
        """Simple body plate should compile without errors."""
        script = generate_openscad([], {"body_width": 100, "body_height": 80})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Body with dimensions ──

    @skip_no_openscad
    def test_body_with_custom_dimensions_compiles(self, tmp_path: Path) -> None:
        """Body with non-default dimensions should compile."""
        script = generate_openscad([], {"body_width": 200, "body_height": 150, "body_thickness": 8})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Hole (drill) ──

    @skip_no_openscad
    def test_hole_only_compiles(self, hole_only_tree: dict, tmp_path: Path) -> None:
        """Script with a single drill hole should compile."""
        script = generate_openscad(hole_only_tree["operations"], hole_only_tree["parameters"])
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── All operation types ──

    @skip_no_openscad
    def test_all_operations_compiles(self, all_operations_tree: dict, tmp_path: Path) -> None:
        """Script with all 8 operation types should compile."""
        script = generate_openscad(
            all_operations_tree["operations"],
            all_operations_tree["parameters"],
        )
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Vent slots (horizontal) ──

    @skip_no_openscad
    def test_vent_horizontal_compiles(self, tmp_path: Path) -> None:
        """Script with horizontal vent slots should compile."""
        ops = [{
            "operation": "vent_cut", "feature_id": "vent_1",
            "x": 150, "y": 250, "width": 100, "height": 80,
            "slot_count": 5, "orientation": "horizontal",
        }]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Vent slots (vertical) ──

    @skip_no_openscad
    def test_vent_vertical_compiles(self, tmp_path: Path) -> None:
        """Script with vertical vent slots should compile."""
        ops = [{
            "operation": "vent_cut", "feature_id": "vent_1",
            "x": 150, "y": 250, "width": 80, "height": 100,
            "slot_count": 4, "orientation": "vertical",
        }]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Boss (additive) ──

    @skip_no_openscad
    def test_boss_compiles(self, tmp_path: Path) -> None:
        """Script with boss extrude should compile."""
        ops = [{"operation": "boss_extrude", "feature_id": "boss_1",
                "x": 300, "y": 80, "radius": 25}]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Mill slot ──

    @skip_no_openscad
    def test_mill_slot_compiles(self, tmp_path: Path) -> None:
        """Script with a mill slot should compile."""
        ops = [{"operation": "mill", "feature_id": "slot_1",
                "x": 150, "y": 100, "width": 80, "height": 20}]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Pocket mill ──

    @skip_no_openscad
    def test_pocket_mill_compiles(self, tmp_path: Path) -> None:
        """Script with a pocket mill should compile."""
        ops = [{"operation": "pocket_mill", "feature_id": "pocket_1",
                "x": 180, "y": 180, "width": 60, "height": 60}]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Empty body (no operations, no parameters) ──

    @skip_no_openscad
    def test_empty_operations_compiles(self, tmp_path: Path) -> None:
        """Script with no operations and no parameters should still compile."""
        script = generate_openscad([], {})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ── Vent + hole combined ──

    @skip_no_openscad
    def test_vent_and_hole_compiles(self, tmp_path: Path) -> None:
        """Script with subtractive AND additive operations should compile."""
        ops = [
            {"operation": "drill", "feature_id": "hole_1",
             "x": 100, "y": 100, "radius": 15},
            {"operation": "boss_extrude", "feature_id": "boss_1",
             "x": 300, "y": 80, "radius": 25},
        ]
        script = generate_openscad(ops, {"body_width": 400, "body_height": 400})
        result = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert result.returncode == 0, (
            f"OpenSCAD compilation failed (exit {result.returncode}):\n"
            f"{result.stderr}"
        )

    # ─── Integration test: full pipeline → Agent 6 → write file → openscad ──

    @skip_no_openscad
    def test_agent_generated_script_compiles(self, agent: CADGenerationAgent, tmp_path: Path) -> None:
        """Script generated by the full Agent 6 pipeline should compile."""
        tree = {
            "operations": [
                {"operation": "drill", "feature_id": "hole_1",
                 "x": 100, "y": 120, "radius": 30},
            ],
            "parameters": {"body_width": 400, "body_height": 350},
        }
        result = agent.process(tree)
        script = result["openscad_script"]
        validation = TestOpenSCADSyntaxValidation._run_openscad(script, tmp_path)
        assert validation.returncode == 0, (
            f"Agent 6-generated OpenSCAD failed to compile (exit {validation.returncode}):\n"
            f"{validation.stderr}"
        )
